name: Build wayblue-nvidia
on:
  schedule:
    - cron: "0 0 * * *" # Build daily to stay updated
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  bluebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and Sign Image
        uses: blue-build/github-action@v1.1
        with:
          recipe: recipe.yml # Point to your recipe file
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
